<a href="https://colab.research.google.com/github/klbailey/NeuralNetwork/blob/main/Intro_Neural.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

Tensors: A torch. Tensor is a multi-dimensional matrix containing elements of a single data type. Similary to numpy arrays but on GPU; default data type of float32;

I am using torch  2.4.1+cu121

##Lists

In [3]:
my_list = [1, 2, 3, 4, 5]
my_list

[1, 2, 3, 4, 5]

##Numpy arrays

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.6030215 , 0.19124738, 0.08099752, 0.53601341],
       [0.20454563, 0.18562397, 0.97776159, 0.86871582],
       [0.91308426, 0.33883638, 0.27801521, 0.12857529]])

##Tensors

In [5]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.5371, -0.2165,  0.3073,  0.2460],
        [ 1.3586, -2.3084, -0.3938, -0.6585],
        [ 0.6281, -1.6081, -0.3449,  1.0065]])

In [6]:
#Create tensor out of numpy array is float 64 because that's what numpy array is tensor holds the data
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6030, 0.1912, 0.0810, 0.5360],
        [0.2045, 0.1856, 0.9778, 0.8687],
        [0.9131, 0.3388, 0.2780, 0.1286]], dtype=torch.float64)

##Operations

In [7]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
#Reshape if we don't know number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
#can do in opposite direction
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
# Use view
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Reshape and view, they will update when you make change to original tensor it updates

In [17]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [20]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

Slices - grab a section of the tensor

In [21]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
#Get 7th item
my_torch7[7]

tensor(7)

In [23]:
#slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [24]:
#Get 2nd column
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [25]:
#Keep shape/return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])